const I18N = {
    tr: {
        loading: "YÜKLENİYOR...",
        startingFarm: "Başlangıç Çiftliği",
        money: "Para:",
        ranking: "Sıralama",
        wipeSave: "Kaydı Sil",
        shopTitle: "Pazar",
        buyChicken: "Tavuk Satın Al",
        buyChickenDesc: "Yumurtlayan yeni bir dost. (+1 Tavuk)",
        happyPetting: "Mutlu Sevmeler",
        happyPettingDesc: "Tavuklarını mutlu etmek için onları sev. Her sevdiğinde yumurtlama süresi azalır. (Sevme başına -1.0sn Yumurtlama Süresi)",
        eggValue: "Yumurta Fiyatı",
        eggValueDesc: "Tüm yumurtaların temel kalitesini artırır. (x1.5 Değer)",
        eggRamp: "Yumurta Rampası",
        eggRampDesc: "Düşen yumurtaların yeraltı bandına düzgünce sekmesini sağlayan ahşap bir takoz ekler. (Oylamayla en gereksiz geliştirme seçildi)",
        maxFood: "Maksimum Yem",
        maxFoodDesc: "Yemlik kapasitesini artırır.",
        maxWater: "Maksimum Su",
        maxWaterDesc: "Suluk kapasitesini artırır.",
        eggWasher: "Yumurta Yıkayıcı",
        eggWasherDesc: "Piyasa değerini artırmak için yumurtaları temizler. (x2 Çarpan)",
        autoFood: "Otomatik Yem",
        autoFoodDesc: "Yem doldurmayı otomatikleştirir.",
        autoWater: "Otomatik Su",
        autoWaterDesc: "Su doldurmayı otomatikleştirir.",
        farmBelt: "Çiftlik Bandı",
        farmBeltDesc: "Çayır yumurtalarını otomatik taşır.",
        storageBelt: "Depolama Bandı",
        storageBeltDesc: "Depolanmış yumurtaları otomatik olarak pazara taşır.",
        refill: "Doldurma",
        refillDesc: "Elle yapılan etkileşimlerin etkisini artırır.",
        premiumFeed: "Kaliteli Yem (+%5)",
        premiumFeedDesc: "Yüksek kaliteli yumurta bırakma şansı sağlar. (+%5 Şans / x2 Değer)",
        goldenEgg: "Altın Yumurta (+%1)",
        goldenEggDesc: "Efsanevi altın yumurta şansı. (+%1 Şans / x5 Çarpan)",
        qualityStamp: "Kalite Damgası",
        qualityStampDesc: "Daha yüksek bir pazar fiyatı için yumurta kalitesini onaylar. (x2  Çarpan)",
        eggPackager: "Yumurta Paketleyici",
        eggPackagerDesc: "Yumurtaları düzineyle paketler ve büyük kâr getirir. (x2 Değer Çarpanı)",
        premiumBox: "Lüks Kutu",
        premiumBoxDesc: "Yumurtalarını lüks mat siyah ve altın yaldızlı ambalajla paketler. (x2 Değer Çarpanı)",
        farmMusic: "Çiftlik Müziği",
        farmMusicDesc: "Neşeli müzikler çalar, tavukları hızlandırır. (+%15 Hız)",
        proDiet: "Pro Diyet",
        proDietDesc: "Yumurtlamayı hızlandıran özel beslenme. (-1.0 sn Yumurtlama Süresi)",
        dessertStomach: "Tatlı Midesi",
        dessertStomachDesc: "2 kat yem yer ve öğün aralarında iki kat daha fazla yumurtlar.",
        magnetForce: "Mıknatıs Gücü",
        magnetForceDesc: "İmlecini mıknatıslayarak uzaktan daha fazla yumurta toplar. (+5 px Yarıçap / +1 Kapasite)",
        theRooster: "Horoz",
        theRoosterDesc: "Heybetli bir yol arkadaşı. Zamanla kümesini büyütür. (Belirli aralıklarla 1 civciv oluşturur)",
        growthFormula: "Büyüme Formülü",
        growthFormulaDesc: "Civcivlerin yumurtlayan tavuklara dönüşmesini hızlandırır. (-10 sn Büyüme Süresi)",
        asSeenOnTV: "TV Reklamı",
        asSeenOnTVDesc: "Çiftliğinle ilgili bir reklam viral olur. Tüm yumurtaların satış değerini kalıcı olarak ikiye katlar! (x2 Değer Çarpanı)",
        retire: "Emekli Ol",
        wishlistOnSteam: "STEAM'DE İSTEK LİSTESİNE EKLE!",
        takeABreak: "Biraz mola ver...",
        warning: "UYARI!",
        warningDesc: "TÜM ilerlemeyi silmek istediğinizden emin misiniz?<br><br>Bu işlem geri alınamaz!",
        cancel: "İPTAL",
        wipeIt: "HEPSİNİ SİL",
        pause: "DURAKLAT",
        resume: "DEVAM ET",
        speedrunRanking: "SPEEDRUN SIRALAMASI",
        connecting: "Sunucuya bağlanılıyor...",
        speedrunWarning: "Speedrun Modu tüm yumurta değerlerini ikiye katlar (x2).<br><br>Yalnızca Speedrun koşuları sıralamaya yüklenir!",
        startSpeedrun: "SPEEDRUN'I BAŞLAT",
        normalMode: "NORMAL MOD",
        close: "KAPAT",
        newRecord: "YENİ REKOR!",
        time: "SÜRE:",
        chickensFreed: "Kurtarılan Tavuk:",
        enterName: "Sıralama için isminizi girin:",
        community: "Topluluk:",
        submitScore: "SKORU GÖNDER",
        yourNamePlaceholder: "İSMİNİZ",

        // JS Texts
        market: "PAZAR",
        fill: "Doldur",
        water: "SU:",
        food: "YEM:",
        waterEmpty: "Su bitti,",
        foodEmpty: "Yem bitti,",
        clickToRefill: "doldurmak için tıkla ",
        playtime: "Oynama Süresi:",
        eggsSold: "Satılan Yumurta:",
        earnings: "Kazanç:",
        chickens: "Tavuklar:",
        selectCommunity: "-- TOPLULUK SEÇ --",
        //Hasta aqui traducido real
        challenges: "MEYDAN OKUMALAR",
        chal1Title: "1. NORMAL (SAKİN)",
        chal1Desc: "Sıralama yok, ceza yok. Kendi hızında geliş ve emeklilik hedefine güvenle ulaş.",
        playMode: "NORMAL OYNA",
        chal2Title: "4. SPEEDRUN",
        chal2Desc: "Yumurta değerleri iki katına çıkar (x2). Sona olabildiğince hızlı ulaş. Bitirme süren Küresel Sıralamaya yazılır!",
        viewGlobalRanking: "KÜRESEL SIRALAMAYI GÖR",
        playSpeedrun: "SPEEDRUN OYNA",
        chal3Title: "2. ADEM & HAVVA",
        chal3Desc: "Sadece 1 Horoz ve 1 Tavuk ile başla. Çiftliği sevgiyle yeniden canlandır. En fazla 5 horoz olabilir!",
        playAdam: "MEYDAN OKUMA OYNA",
        chal4Title: "3. YUMURTA SIKIŞMASI",
        chal4Desc: "Taşıma bandı bozuldu! Ama mıknatısın çok daha güçlü. Yumurtaları bodruma elle sürükle.",
        playManual: "GÖREVİ OYNA",
        adamGameOver: "OYUN BİTTİ! Bir tavuk açlıktan öldü. Adem & Havva yeniden başlatılıyor...",
        locked: "KİLİTLİ",
    },
    ru: {
        loading: "ЗАГРУЗКА...",
        startingFarm: "Запуск фермы",
        money: "ДЕНЬГИ:",
        ranking: "РЕЙТИНГ",
        wipeSave: "УДАЛИТЬ",
        shopTitle: "Магазин",
        buyChicken: "Купить курицу",
        buyChickenDesc: "Новая подруга-несушка. (+1 Курица)",
        happyPetting: "Счастливые ласки",
        happyPettingDesc: "Гладьте своих кур. Каждое поглаживание уменьшает время снесения яйца на 1с.",
        eggValue: "Ценность яйца",
        eggValueDesc: "Увеличивает врожденное качество всех яиц. (x1.5 Базовая стоимость)",
        eggRamp: "Яичный пандус",
        eggRampDesc: "Деревянный клин для яиц. (Самое бесполезное улучшение)",
        maxFood: "Макс еда",
        maxFoodDesc: "Увеличивает вместимость кормушки.",
        maxWater: "Макс вода",
        maxWaterDesc: "Увеличивает вместимость поилки.",
        eggWasher: "Мойка яиц",
        eggWasherDesc: "Очищает яйца для увеличения их рыночной стоимости. (x2 к стоимости)",
        autoFood: "Авто-еда",
        autoFoodDesc: "Автоматическое пополнение еды.",
        autoWater: "Авто-вода",
        autoWaterDesc: "Автоматическое пополнение воды.",
        farmBelt: "Ферм. конвейер",
        farmBeltDesc: "Автоматическая транспортировка луговых яиц вниз.",
        storageBelt: "Склад. конвейер",
        storageBeltDesc: "Автоматическая транспортировка яиц на рынок.",
        refill: "Наполнение",
        refillDesc: "Увеличивает силу ручного взаимодействия.",
        premiumFeed: "Премиум корм (+5%)",
        premiumFeedDesc: "Шанс снести высококачественные яйца. (+5% Шанс / x2 к стоимости)",
        goldenEgg: "Золотое яйцо (+1%)",
        goldenEggDesc: "Шанс снести золотые яйца. (+1% Шанс / x5 к стоимости)",
        qualityStamp: "Знак качества",
        qualityStampDesc: "Сертифицирует качество яйца. (x2 к стоимости)",
        eggPackager: "Упаковщик яиц",
        eggPackagerDesc: "Упаковывает яйца дюжинами для прибыли. (x2 к стоимости)",
        premiumBox: "Премиум коробка",
        premiumBoxDesc: "Черная упаковка с золотой фольгой. (x2 к стоимости)",
        farmMusic: "Ферм. музыка",
        farmMusicDesc: "Веселые мелодии заставляют кур двигаться быстрее. (+15% Скорости)",
        proDiet: "Профи-диета",
        proDietDesc: "Специализированное питание ускоряет снесение яиц. (-1.0с Время)",
        dessertStomach: "Десертный желудок",
        dessertStomachDesc: "Съедает в 2 раза больше и несет в 2 раза больше яиц.",
        magnetForce: "Магнитная сила",
        magnetForceDesc: "Намагничивает курсор для захвата яиц на расстоянии.",
        theRooster: "Петух",
        theRoosterDesc: "Величественный спутник. Периодически создает 1 цыпленка.",
        growthFormula: "Формула роста",
        growthFormulaDesc: "Ускоряет время взросления цыпленка на 10с.",
        asSeenOnTV: "Звезда ТВ",
        asSeenOnTVDesc: "Вирусная реклама удваивает стоимость всех яиц навсегда! (x2 к стоимости)",
        retire: "Уйти на пенсию",
        wishlistOnSteam: "В СПИСОК ЖЕЛАЕМОГО",
        takeABreak: "Сделайте перерыв...",
        warning: "ВНИМАНИЕ!",
        warningDesc: "Вы уверены? Весь прогресс будет удален!<br><br>Это действие нельзя отменить!",
        cancel: "ОТМЕНА",
        wipeIt: "УДАЛИТЬ",
        pause: "ПАУЗА",
        resume: "ПРОДОЛЖИТЬ",
        speedrunRanking: "РЕЙТИНГ СПИДРАНА",
        connecting: "Подключение к серверу...",
        speedrunWarning: "Режим спидрана удваивает (x2) стоимость яиц.<br><br>Только спидраны загружаются в рейтинг!",
        startSpeedrun: "НАЧАТЬ СПИДРАН",
        normalMode: "ОБЫЧНЫЙ РЕЖИМ",
        close: "ЗАКРЫТЬ",
        newRecord: "НОВЫЙ РЕКОРД!",
        time: "ВРЕМЯ:",
        chickensFreed: "Освобождено:",
        enterName: "Введите ваше имя для рейтинга:",
        community: "Сообщество:",
        submitScore: "ОТПРАВИТЬ СЧЕТ",
        yourNamePlaceholder: "ВАШЕ ИМЯ",

        // JS Texts
        market: "РЫНОК",
        fill: "Лить",
        water: "ВОДА:",
        food: "ЕДА:",
        waterEmpty: "Вода пуста,",
        foodEmpty: "Еда пуста,",
        clickToRefill: "клик для пополнения ",
        playtime: "Время в игре:",
        eggsSold: "Продано яиц:",
        earnings: "Заработок:",
        chickens: "Куры:",
        selectCommunity: "-- ВЫБРАТЬ --",
        challenges: "ИСПЫТАНИЯ",
        chal1Title: "1. НОРМАЛЬНЫЙ (RELAX)",
        chal1Desc: "Никаких рейтингов, никакой спешки. Развивайтесь в своем темпе и благополучно доберитесь до выхода на пенсию.",
        playMode: "ИГРАТЬ ОБЫЧНО",
        chal2Title: "4. SPEEDRUN",
        chal2Desc: "Стоимость яиц удваивается (x2). Пройдите как можно быстрее. Ваше время попадет в Глобальный Рейтинг!",
        viewGlobalRanking: "СМОТРЕТЬ ГЛОБАЛЬНЫЙ РЕЙТИНГ",
        playSpeedrun: "ИГРАТЬ SPEEDRUN",
        chal3Title: "2. АДАМ И ЕВА",
        chal3Desc: "Вы начинаете строго с 1 Петухом и 1 Курицей. Заселите ферму с любовью, Максимум 5 петухов.",
        playAdam: "ИГРАТЬ ИСПЫТАНИЕ",
        chal4Title: "3. ЗАСТРЯВШИЕ ЯЙЦА",
        chal4Desc: "Фермерская лента порвалась! Но ваш магнит намного мощнее. Вручную перетаскивайте яйца в подвал.",
        playManual: "ИГРАТЬ ИСПЫТАНИЕ",
        adamGameOver: "ИГРА ОКОНЧЕНА! Курица умерла от голода. Перезапуск Адама и Евы...",
        locked: "ЗАБЛОКИРОВАНО",
    },
    de: {
        loading: "LÄDT...",
        startingFarm: "Starte Farm",
        money: "GELD:",
        ranking: "RANGLISTE",
        wipeSave: "LÖSCHEN",
        shopTitle: "Laden",
        buyChicken: "Huhn kaufen",
        buyChickenDesc: "Ein neuer Legefreund. (+1 Huhn)",
        happyPetting: "Glückliches Streicheln",
        happyPettingDesc: "Streichle deine Hühner. Jedes Streicheln reduziert die Legezeit. (-1.0s Legezeit)",
        eggValue: "Ei-Wert",
        eggValueDesc: "Erhöht die Qualität aller Eier. (x1.5 Wert)",
        eggRamp: "Eierrampe",
        eggRampDesc: "Verhindert, dass Eier stecken bleiben. (Nutzlosestes Upgrade)",
        maxFood: "Max Futter",
        maxFoodDesc: "Erweitert die Trogkapazität.",
        maxWater: "Max Wasser",
        maxWaterDesc: "Erweitert die Beckenkapazität.",
        eggWasher: "Eierwäscher",
        eggWasherDesc: "Reinigt Eier, um ihren Marktwert zu erhöhen. (x2 Wert)",
        autoFood: "Auto-Futter",
        autoFoodDesc: "Automatisiert das Nachfüllen von Futter.",
        autoWater: "Auto-Wasser",
        autoWaterDesc: "Automatisiert das Nachfüllen von Wasser.",
        farmBelt: "Farmband",
        farmBeltDesc: "Transportiert Eier automatisch nach unten.",
        storageBelt: "Lagerband",
        storageBeltDesc: "Transportiert gelagerte Eier automatisch zum Markt.",
        refill: "Nachfüllen",
        refillDesc: "Erhöht die Kraft der manuellen Interaktion.",
        premiumFeed: "Premium-Futter (+5%)",
        premiumFeedDesc: "Chance, Premium-Eier zu legen. (+5% Chance / x2 Wert)",
        goldenEgg: "Goldenes Ei (+1%)",
        goldenEggDesc: "Seltene Chance, goldene Eier zu legen. (+1% Chance / x5 Wert)",
        qualityStamp: "Qualitätsstempel",
        qualityStampDesc: "Zertifiziert die Ei-Qualität für höhere Preise. (x2 Wert)",
        eggPackager: "Eierverpacker",
        eggPackagerDesc: "Verpackt Eier in Dutzenden für massiven Profit. (x2 Wert)",
        premiumBox: "Premium-Box",
        premiumBoxDesc: "Verpackt Eier in luxuriöse Goldfolie. (x2 Wert)",
        farmMusic: "Farmmusik",
        farmMusicDesc: "Fröhliche Melodien machen Hühner schneller. (+15% Tempo)",
        proDiet: "Pro-Diät",
        proDietDesc: "Spezielle Ernährung beschleunigt das Legen. (-1.0s Zeit)",
        dessertStomach: "Dessertmagen",
        dessertStomachDesc: "Frisst 2x Futter und legt 2x so viele Eier.",
        magnetForce: "Magnetkraft",
        magnetForceDesc: "Magnetisiert den Mauszeiger, um Eier von fern zu greifen.",
        theRooster: "Der Hahn",
        theRoosterDesc: "Ein majestätischer Gefährte. Erzeugt periodisch 1 Küken.",
        growthFormula: "Wachstumsformel",
        growthFormulaDesc: "Verkürzt die Zeit, bis Küken erwachsen sind. (-10s Zeit)",
        asSeenOnTV: "Aus dem TV",
        asSeenOnTVDesc: "Ein Werbespot geht viral. Verdoppelt den Wert aller Eier! (x2 Wert)",
        retire: "In Rente gehen",
        wishlistOnSteam: "ZUR WUNSCHLISTE",
        takeABreak: "Mach eine Pause...",
        warning: "WARNUNG!",
        warningDesc: "Willst du WIRKLICH deinen gesamten Fortschritt löschen?<br><br>Dies kann nicht rückgängig gemacht werden!",
        cancel: "ABBRECHEN",
        wipeIt: "LÖSCHEN",
        pause: "PAUSE",
        resume: "WEITER",
        speedrunRanking: "SPEEDRUN-RANGLISTE",
        connecting: "Verbinde mit Server...",
        speedrunWarning: "Im Speedrun-Modus verdoppelt sich (x2) der Ei-Wert.<br><br>Nur Speedrun-Durchläufe kommen in die Rangliste!",
        startSpeedrun: "SPEEDRUN STARTEN",
        normalMode: "NORMALER MODUS",
        close: "SCHLIESSEN",
        newRecord: "NEUER REKORD!",
        time: "ZEIT:",
        chickensFreed: "Befreite Hühner:",
        enterName: "Gib deinen Namen für die Rangliste ein:",
        community: "Community:",
        submitScore: "PUNKTZAHL SENDEN",
        yourNamePlaceholder: "DEIN NAME",
        targetMkt: "MARKT",
        fill: "Füllen",
        water: "WASSER:",
        food: "FUTTER:",
        waterEmpty: "Wasser leer,",
        foodEmpty: "Futter leer,",
        clickToRefill: "zum Füllen klicken ",
        playtime: "Spielzeit:",
        eggsSold: "Verkaufte Eier:",
        earnings: "Einnahmen:",
        chickens: "Hühner:",
        selectCommunity: "-- COMMUNITY WÄHLEN --",
        challenges: "HERAUSFORDERUNGEN",
        chal1Title: "1. NORMAL (RELAX)",
        chal1Desc: "Kein Ranking, keine Eile. Wachse in deinem eigenen Tempo und erreiche sicher den Ruhestand.",
        playMode: "NORMAL SPIELEN",
        chal2Title: "4. SPEEDRUN",
        chal2Desc: "Eierwerte sind verdoppelt (x2). Beende es so schnell wie möglich. Deine Zeit geht ins Globale Ranking!",
        viewGlobalRanking: "GLOBALES RANKING ANSEHEN",
        playSpeedrun: "SPEEDRUN SPIELEN",
        chal3Title: "2. ADAM & EVA",
        chal3Desc: "Du beginnst strikt mit 1 Hahn und 1 Henne. Bevölkere die Farm mit viel Liebe, Max 5 Hähne.",
        playAdam: "HERAUSFORDERUNG SPIELEN",
        chal4Title: "3. EIERSTAU",
        chal4Desc: "Das Farmband ist gerissen! Aber dein Magnet ist viel stärker. Ziehe die Eier manuell in den Keller.",
        playManual: "HERAUSFORDERUNG SPIELEN",
        adamGameOver: "SPIEL VORBEI! Ein Huhn ist verhungert. Adam & Eva wird neu gestartet...",
        locked: "GESPERRT",
    },
    fr: {
        loading: "CHARGEMENT...",
        startingFarm: "Démarrage...",
        money: "ARGENT:",
        ranking: "CLASSEMENT",
        wipeSave: "EFFACER",
        shopTitle: "Boutique",
        buyChicken: "Poulet",
        buyChickenDesc: "Une nouvelle amie pondeuse. (+1 Poulet)",
        happyPetting: "Câlins Heureux",
        happyPettingDesc: "Caressez vos poules pour les rendre heureuses. (-1.0s Temps de ponte)",
        eggValue: "Valeur de l'Oeuf",
        eggValueDesc: "Améliore la qualité innée des oeufs. (x1.5 Valeur)",
        eggRamp: "Rampe à Oeufs",
        eggRampDesc: "Ajoute un coin en bois. (Amélioration la plus inutile)",
        maxFood: "Max Nourriture",
        maxFoodDesc: "Augmente la capacité de la mangeoire.",
        maxWater: "Max Eau",
        maxWaterDesc: "Augmente la capacité du bassin d'eau.",
        eggWasher: "Laveur d'Oeufs",
        eggWasherDesc: "Nettoie les oeufs pour augmenter leur valeur. (x2 Valeur)",
        autoFood: "Auto-Nourriture",
        autoFoodDesc: "Automatise le remplissage de nourriture.",
        autoWater: "Auto-Eau",
        autoWaterDesc: "Automatise le remplissage d'eau.",
        farmBelt: "Tapis Fermier",
        farmBeltDesc: "Transporte automatiquement les oeufs des prés.",
        storageBelt: "Tapis de Stockage",
        storageBeltDesc: "Transporte automatiquement les oeufs stockés.",
        refill: "Recharger",
        refillDesc: "Améliore la puissance d'interaction manuelle.",
        premiumFeed: "Nourriture Premium (+5%)",
        premiumFeedDesc: "Chance de pondre des oeufs premium. (+5% Chance / x2 Valeur)",
        goldenEgg: "Oeuf d'Or (+1%)",
        goldenEggDesc: "Chance de pondre des oeufs d'or. (+1% Chance / x5 Valeur)",
        qualityStamp: "Timbre de Qualité",
        qualityStampDesc: "Certifie la qualité de l'oeuf pour un meilleur prix. (x2 Valeur)",
        eggPackager: "Emballeur",
        eggPackagerDesc: "Emballe les oeufs par douzaines pour plus de profits. (x2 Valeur)",
        premiumBox: "Boîte Premium",
        premiumBoxDesc: "Enveloppe vos oeufs dans un emballage de luxe. (x2 Valeur)",
        farmMusic: "Musique",
        farmMusicDesc: "Des airs enjoués accélèrent vos poulets. (+15% Vitesse)",
        proDiet: "Régime Pro",
        proDietDesc: "Nutrition spécialisée qui accélère la ponte. (-1.0s Temps)",
        dessertStomach: "Estomac à Dessert",
        dessertStomachDesc: "Mange 2x plus et pond 2x plus d'oeufs.",
        magnetForce: "Force Magnétique",
        magnetForceDesc: "Magnétise votre curseur pour saisir les oeufs à distance.",
        theRooster: "Le Coq",
        theRoosterDesc: "Un compagnon majestueux. Fait naître 1 poussin périodiquement.",
        growthFormula: "Formule de Croissance",
        growthFormulaDesc: "Accélère la maturation des poussins. (-10s Maturation)",
        asSeenOnTV: "Vu à la Télé",
        asSeenOnTVDesc: "Une publicité double la valeur de tous vos oeufs ! (x2 Valeur)",
        retire: "Retraite",
        wishlistOnSteam: "LISTE DE SOUHAITS",
        takeABreak: "Faites une pause...",
        warning: "ATTENTION !",
        warningDesc: "Êtes-vous sûr de vouloir supprimer TOUTE votre progression ?<br><br>Ceci ne peut pas être annulé !",
        cancel: "ANNULER",
        wipeIt: "EFFACER",
        pause: "PAUSE",
        resume: "REPRENDRE",
        speedrunRanking: "CLASSEMENT SPEEDRUN",
        connecting: "Connexion au serveur...",
        speedrunWarning: "Le mode Speedrun double (x2) la valeur des oeufs.<br><br>Seules les parties Speedrun sont classées !",
        startSpeedrun: "LANCER SPEEDRUN",
        normalMode: "MODE NORMAL",
        close: "FERMER",
        newRecord: "NOUVEAU RECORD !",
        time: "TEMPS:",
        chickensFreed: "Poulets Libérés:",
        enterName: "Entrez votre nom pour le classement mondial :",
        community: "Communauté:",
        submitScore: "SOUMETTRE",
        yourNamePlaceholder: "VOTRE NOM",
        market: "MARCHÉ",
        fill: "Remplir",
        water: "EAU:",
        food: "NOURRITURE:",
        waterEmpty: "Plus d'eau,",
        foodEmpty: "Plus de nourriture,",
        clickToRefill: "cliquez pour remplir ",
        playtime: "Temps de jeu:",
        eggsSold: "Oeufs Vendus:",
        earnings: "Gains:",
        chickens: "Poulets:",
        selectCommunity: "-- SÉLECTIONNER --",
        challenges: "DÉFIS",
        chal1Title: "1. NORMAL (RELAX)",
        chal1Desc: "Pas de classement, pas de hâte. Développez-vous à votre rythme et atteignez la retraite en toute sécurité.",
        playMode: "JOUER NORMAL",
        chal2Title: "4. SPEEDRUN",
        chal2Desc: "La valeur des œufs est doublée (x2). Terminez le plus vite possible. Votre temps ira dans le Classement Global !",
        viewGlobalRanking: "VOIR LE CLASSEMENT GLOBAL",
        playSpeedrun: "JOUER SPEEDRUN",
        chal3Title: "2. ADAM & ÈVE",
        chal3Desc: "Vous commencez avec exactement 1 Coq et 1 Poule. Repeuplez la ferme avec amour, Max 5 coqs.",
        playAdam: "JOUER LE DÉFI",
        chal4Title: "3. EMBOUTEILLAGE D'ŒUFS",
        chal4Desc: "Le tapis de la ferme est cassé ! Mais votre aimant est beaucoup plus puissant. Faites glisser les œufs manuellement au sous-sol.",
        playManual: "JOUER LE DÉFI",
        adamGameOver: "FIN DE PARTIE ! Une poule est morte de faim. Redémarrage d'Adam & Ève...",
        locked: "VERROUILLÉ",
    },
    it: {
        loading: "CARICAMENTO...",
        startingFarm: "Avvio della Fattoria",
        money: "DENARO:",
        ranking: "CLASSIFICA",
        wipeSave: "CANCELLA",
        shopTitle: "Negozio",
        buyChicken: "Compra Pollo",
        buyChickenDesc: "Un nuovo amico che depone uova. (+1 Pollo)",
        happyPetting: "Carezze Felici",
        happyPettingDesc: "Accarezza le tue galline. Ogni carezza riduce il tempo di deposizione (-1.0s).",
        eggValue: "Valore Uovo",
        eggValueDesc: "Migliora la qualità di tutte le uova. (x1.5 Valore)",
        eggRamp: "Rampa per Uova",
        eggRampDesc: "Aggiunge un cuneo di legno. (Il potenziamento più inutile)",
        maxFood: "Cibo Max",
        maxFoodDesc: "Espande la capacità della mangiatoia.",
        maxWater: "Acqua Max",
        maxWaterDesc: "Espande la capacità della bacinella.",
        eggWasher: "Lavauova",
        eggWasherDesc: "Pulisce le uova per aumentarne il valore di mercato. (x2 Valore)",
        autoFood: "Auto-Cibo",
        autoFoodDesc: "Automatizza il riempimento del cibo.",
        autoWater: "Auto-Acqua",
        autoWaterDesc: "Automatizza il riempimento dell'acqua.",
        farmBelt: "Nastro Fattoria",
        farmBeltDesc: "Trasporta automaticamente le uova della prateria.",
        storageBelt: "Nastro Magazzino",
        storageBeltDesc: "Trasporta automaticamente le uova immagazzinate al mercato.",
        refill: "Ricarica",
        refillDesc: "Aumenta la potenza dell'interazione manuale.",
        premiumFeed: "Mangime Premium (+5%)",
        premiumFeedDesc: "Possibilità di deporre uova premium. (+5% Probabilità / x2 Valore)",
        goldenEgg: "Uovo d'Oro (+1%)",
        goldenEggDesc: "Possibilità di deporre uova d'oro. (+1% Probabilità / x5 Valore)",
        qualityStamp: "Timbro di Qualità",
        qualityStampDesc: "Certifica la qualità dell'uovo per un prezzo più alto. (x2 Valore)",
        eggPackager: "Confezionatrice",
        eggPackagerDesc: "Confeziona le uova a dozzine per grandi profitti. (x2 Valore)",
        premiumBox: "Scatola Premium",
        premiumBoxDesc: "Avvolge le uova in un packaging nero e oro. (x2 Valore)",
        farmMusic: "Musica Fattoria",
        farmMusicDesc: "I brani allegri fanno muovere le galline più velocemente. (+15% Velocità)",
        proDiet: "Dieta Pro",
        proDietDesc: "Nutrizione specializzata per deporre più in fretta. (-1.0s Tempo)",
        dessertStomach: "Stomaco da Dessert",
        dessertStomachDesc: "Mangia il doppio e depone il doppio delle uova.",
        magnetForce: "Forza Magnetica",
        magnetForceDesc: "Magnetizza il cursore per prendere le uova a distanza.",
        theRooster: "Il Gallo",
        theRoosterDesc: "Un compagno maestoso. Genera 1 pulcino periodicamente.",
        growthFormula: "Formula di Crescita",
        growthFormulaDesc: "Accelera la crescita dei pulcini in galline. (-10s Tempo)",
        asSeenOnTV: "Visto in TV",
        asSeenOnTVDesc: "Una pubblicità diventa virale. Raddoppia permanentemente il valore delle uova! (x2 Valore)",
        retire: "Ritirati",
        wishlistOnSteam: "LISTA DESIDERI",
        takeABreak: "Prenditi una pausa...",
        warning: "ATTENZIONE!",
        warningDesc: "Sei sicuro di voler cancellare TUTTI i progressi?<br><br>Questa operazione non è reversibile!",
        cancel: "ANNULLA",
        wipeIt: "CANCELLA",
        pause: "PAUSA",
        resume: "RIPRENDI",
        speedrunRanking: "CLASSIFICA SPEEDRUN",
        connecting: "Connessione al server...",
        speedrunWarning: "La modalità Speedrun raddoppia (x2) il valore delle uova.<br><br>Solo gli Speedrun vanno in classifica!",
        startSpeedrun: "INIZIA SPEEDRUN",
        normalMode: "MODALITÀ NORMALE",
        close: "CHIUDI",
        newRecord: "NUOVO RECORD!",
        time: "TEMPO:",
        chickensFreed: "Galline Liberate:",
        enterName: "Inserisci il tuo nome per la classifica:",
        community: "Comunità:",
        submitScore: "INVIA PUNTEGGIO",
        yourNamePlaceholder: "IL TUO NOME",
        market: "MERCATO",
        fill: "Riempi",
        water: "ACQUA:",
        food: "CIBO:",
        waterEmpty: "Acqua finita,",
        foodEmpty: "Cibo finito,",
        clickToRefill: "clicca per riempire ",
        playtime: "Tempo di Gioco:",
        eggsSold: "Uova Vendute:",
        earnings: "Guadagni:",
        chickens: "Polli:",
        selectCommunity: "-- SELEZIONA --",
        challenges: "SFIDE",
        chal1Title: "1. NORMALE (RELAX)",
        chal1Desc: "Nessuna classifica, nessuna fretta. Cresci al tuo ritmo e raggiungi la pensione in sicurezza.",
        playMode: "GIOCA NORMALE",
        chal2Title: "4. SPEEDRUN",
        chal2Desc: "I valori delle uova sono raddoppiati (x2). Finisci il più velocemente possibile. Il tuo tempo andrà nella Classifica Globale!",
        viewGlobalRanking: "VEDI LA CLASSIFICA GLOBALE",
        playSpeedrun: "GIOCA SPEEDRUN",
        chal3Title: "2. ADAMO ED EVA",
        chal3Desc: "Inizi rigorosamente con 1 Gallo e 1 Gallina. Ripopola la fattoria con tanto amore, Max 5 galli.",
        playAdam: "GIOCA LA SFIDA",
        chal4Title: "3. INGORGO DI UOVA",
        chal4Desc: "Il nastro della fattoria si è rotto! Ma il tuo magnete è molto più potente. Trascina manualmente le uova in cantina.",
        playManual: "GIOCA LA SFIDA",
        adamGameOver: "GAME OVER! Una gallina è morta di fame. Riavvio di Adamo ed Eva...",
        locked: "BLOCCATO",
    },
    'pt-br': {
        loading: "CARREGANDO...",
        startingFarm: "Iniciando Fazenda",
        money: "DINHEIRO:",
        ranking: "RANKING",
        wipeSave: "APAGAR SAVES",
        shopTitle: "Loja",
        buyChicken: "Galinha",
        buyChickenDesc: "Uma nova amiga poedeira. (+1 Galinha)",
        happyPetting: "Carinhos Felizes",
        happyPettingDesc: "Acaricie suas galinhas para deixá-las felizes. (-1.0s Tempo de postura)",
        eggValue: "Valor do Ovo",
        eggValueDesc: "Melhora a qualidade inata de todos os ovos. (x1.5 Valor)",
        eggRamp: "Rampa de Ovos",
        eggRampDesc: "Adiciona uma cunha de madeira. (A melhoria mais inútil)",
        maxFood: "Comida Max",
        maxFoodDesc: "Expande a capacidade do comedouro.",
        maxWater: "Água Max",
        maxWaterDesc: "Expande a capacidade do bebedouro.",
        eggWasher: "Lavadora de Ovos",
        eggWasherDesc: "Limpa os ovos para aumentar seu valor de mercado. (x2 Valor)",
        autoFood: "Auto-Comida",
        autoFoodDesc: "Automatiza o refil de comida.",
        autoWater: "Auto-Água",
        autoWaterDesc: "Automatiza o refil de água.",
        farmBelt: "Esteira",
        farmBeltDesc: "Transporta automaticamente os ovos do prado.",
        storageBelt: "Esteira de Armazém",
        storageBeltDesc: "Transporta os ovos armazenados ao mercado.",
        refill: "Refil",
        refillDesc: "Aumenta o poder da interação manual.",
        premiumFeed: "Ração Premium (+5%)",
        premiumFeedDesc: "Chance de botar ovos premium. (+5% Chance / x2 Valor)",
        goldenEgg: "Ovo Dourado (+1%)",
        goldenEggDesc: "Chance rara de botar ovos dourados. (+1% Chance / x5 Valor)",
        qualityStamp: "Selo de Qualidade",
        qualityStampDesc: "Certifica a qualidade do ovo para um preço mais alto. (x2 Valor)",
        eggPackager: "Empacotador",
        eggPackagerDesc: "Embala os ovos em dúzias para maiores lucros. (x2 Valor)",
        premiumBox: "Caixa Premium",
        premiumBoxDesc: "Envolve seus ovos em luxuosas embalagens pretas e douradas. (x2 Valor)",
        farmMusic: "Música",
        farmMusicDesc: "Músicas alegres deixam as galinhas mais rápidas. (+15% Vel)",
        proDiet: "Dieta Pro",
        proDietDesc: "Nutrição especializada que acelera a postura. (-1.0s Tempo)",
        dessertStomach: "Estômago de Doces",
        dessertStomachDesc: "Come o dobro de comida e bota o dobro de ovos.",
        magnetForce: "Força Magnética",
        magnetForceDesc: "Magnetiza o cursor para pegar mais ovos a distância.",
        theRooster: "O Galo",
        theRoosterDesc: "Um companheiro majestoso. Gera 1 pintinho periodicamente.",
        growthFormula: "Fórmula Crescimento",
        growthFormulaDesc: "Acelera o tempo de maturação de pintinho a galinha. (-10s Tempo)",
        asSeenOnTV: "Visto na TV",
        asSeenOnTVDesc: "Um comercial viraliza. Dobra permanentemente o valor! (x2 Valor)",
        retire: "Aposentar-se",
        wishlistOnSteam: "LISTA DE DESEJOS",
        takeABreak: "Faça uma pausa...",
        warning: "AVISO!",
        warningDesc: "Tem certeza de que deseja apagar TODO o progresso?<br><br>Isso não pode ser desfeito!",
        cancel: "CANCELAR",
        wipeIt: "APAGAR TUDO",
        pause: "PAUSA",
        resume: "VOLTAR",
        speedrunRanking: "RANKING SPEEDRUN",
        connecting: "Conectando...",
        speedrunWarning: "O Modo Speedrun dobra (x2) o valor de todos os ovos.<br><br>Apenas Speedruns vão para o Ranking!",
        startSpeedrun: "INICIAR SPEEDRUN",
        normalMode: "MODO NORMAL",
        close: "FECHAR",
        newRecord: "NOVO RECORDE!",
        time: "TEMPO:",
        chickensFreed: "Libertas:",
        enterName: "Digite seu nome para o ranking:",
        community: "Comunidade:",
        submitScore: "ENVIAR",
        yourNamePlaceholder: "SEU NOME",
        market: "MERCADO",
        fill: "Encher",
        water: "ÁGUA:",
        food: "COMIDA:",
        waterEmpty: "Sem água,",
        foodEmpty: "Sem comida,",
        clickToRefill: "clique para encher ",
        playtime: "Tempo Jogado:",
        eggsSold: "Ovos Vendidos:",
        earnings: "Lucros:",
        chickens: "Galinhas:",
        selectCommunity: "-- SELECIONAR --"
    },
    pl: {
        loading: "ŁADOWANIE...",
        startingFarm: "Uruchamianie farmy",
        money: "PIENIĄDZE:",
        ranking: "RANKING",
        wipeSave: "USUŃ ZAPIS",
        shopTitle: "Sklep",
        buyChicken: "Kup Kurczaka",
        buyChickenDesc: "Nowa nioska. (+1 Kurczak)",
        happyPetting: "Głaskanie",
        happyPettingDesc: "Głaszcz kury, by były szczęśliwe. (-1.0s Czas znoszenia)",
        eggValue: "Wartość Jajka",
        eggValueDesc: "Zwiększa bazową jakość jaj. (x1.5 Wartość)",
        eggRamp: "Szyna na Jajka",
        eggRampDesc: "Dodaje drewniany klin. (Najbardziej bezużyteczne ulepszenie)",
        maxFood: "Max. Jedzenie",
        maxFoodDesc: "Zwiększa pojemność karmnika.",
        maxWater: "Max. Woda",
        maxWaterDesc: "Zwiększa pojemność poidła.",
        eggWasher: "Myjka Jaj",
        eggWasherDesc: "Myje jaja, znacznie zwiększając ich wartość. (x2 Wartość)",
        autoFood: "Auto-Jedzenie",
        autoFoodDesc: "Automatycznie uzupełnia jedzenie.",
        autoWater: "Auto-Woda",
        autoWaterDesc: "Automatycznie uzupełnia wodę.",
        farmBelt: "Taśma",
        farmBeltDesc: "Automatycznie transportuje jaja w dół.",
        storageBelt: "Taśma Mag.",
        storageBeltDesc: "Automatycznie transportuje przechowywane jaja na rynek.",
        refill: "Uzupełnianie",
        refillDesc: "Zwiększa siłę manualnej interakcji.",
        premiumFeed: "Pasza Premium (+5%)",
        premiumFeedDesc: "Szansa na zniesienie jaj premium. (+5% Szansy / x2 Wartość)",
        goldenEgg: "Złote Jajo (+1%)",
        goldenEggDesc: "Szansa na legendarne jajo. (+1% Szansy / x5 Wartość)",
        qualityStamp: "Znak Jakości",
        qualityStampDesc: "Certyfikuje jakość jajka na wyższą cenę. (x2 Wartość)",
        eggPackager: "Pakowarka",
        eggPackagerDesc: "Pakuje jaja w tuziny dla ogromnych zysków. (x2 Wartość)",
        premiumBox: "Premium",
        premiumBoxDesc: "Pakuje jaja w luksusowe folie. (x2 Wartość)",
        farmMusic: "Muzyka Farmy",
        farmMusicDesc: "Skoczna muzyka przyspiesza kury. (+15% Prędkość)",
        proDiet: "Dieta Pro",
        proDietDesc: "Specjalistyczne odżywianie. (-1.0s Czas)",
        dessertStomach: "Żołądek na Deser",
        dessertStomachDesc: "Zjada dwa razy więcej, znosi dwa razy więcej jaj.",
        magnetForce: "Siła Magnesu",
        magnetForceDesc: "Ułatwia chwytanie jaj z dystansu.",
        theRooster: "Kogut",
        theRoosterDesc: "Okresowo sprowadza 1 kurczaka.",
        growthFormula: "Formuła Wzrostu",
        growthFormulaDesc: "Skraca czas dorastania piskląt. (-10s Czas)",
        asSeenOnTV: "Znane z TV",
        asSeenOnTVDesc: "Reklama! Podwaja wartość jaj na zawsze! (x2 Wartość)",
        retire: "Zakończ",
        wishlistOnSteam: "DODAJ DO ŻYCZEŃ",
        takeABreak: "Zrób przerwę...",
        warning: "UWAGA!",
        warningDesc: "Czy na pewno chcesz usunąć CAŁY postęp?<br><br>Tej operacji nie można cofnąć!",
        cancel: "ANULUJ",
        wipeIt: "USUŃ WSZYSTKO",
        pause: "PAUZA",
        resume: "WZNÓW",
        speedrunRanking: "RANKING SPEEDRUN",
        connecting: "Łączenie...",
        speedrunWarning: "Tryb Speedrun podwaja (x2) wartość jaj.",
        startSpeedrun: "ZACZNIJ SPEEDRUN",
        normalMode: "TRYB NORMALNY",
        close: "ZAMKNIJ",
        newRecord: "NOWY REKORD!",
        time: "CZAS:",
        chickensFreed: "Uwolnione kury:",
        enterName: "Wpisz imię do rankingu:",
        community: "Społeczność:",
        submitScore: "WYŚLIJ WYNIK",
        yourNamePlaceholder: "TWOJE IMIĘ",
        toggleMusic: "Włącz muzykę",
        toggleInfo: "Pokaż informacje",
        market: "RYNEK",
        fill: "Uzupełnij",
        water: "WODA:",
        food: "KARMA:",
        waterEmpty: "Brak wody,",
        foodEmpty: "Brak karmy,",
        clickToRefill: "kliknij by napełnić ",
        playtime: "Czas gry:",
        eggsSold: "Sprzedane Jaja:",
        earnings: "Zarobki:",
        chickens: "Kurczaki:",
        selectCommunity: "-- WYBIERZ --",
        challenges: "WYZWANIA",
        chal1Title: "1. NORMALNY (RELAX)",
        chal1Desc: "Brak rankingów, bez pośpiechu. Rozwijaj się we własnym tempie i bezpiecznie dotrzyj do emerytury.",
        playMode: "GRAJ NORMALNIE",
        chal2Title: "4. SPEEDRUN",
        chal2Desc: "Wartość jaj jest podwojona (x2). Ukończ jak najszybciej. Twój czas trafi do Globalnego Rankingu!",
        viewGlobalRanking: "ZOBACZ GLOBALNY RANKING",
        playSpeedrun: "GRAJ SPEEDRUN",
        chal3Title: "2. ADAM I EWA",
        chal3Desc: "Zaczynasz ściśle od 1 Koguta i 1 Kury. Z miłością odbuduj populację farmy, Max 5 kogutów.",
        playAdam: "GRAJ W WYZWANIE",
        chal4Title: "3. ZATOR JAJ",
        chal4Desc: "Taśma na farmie się zerwała! Ale twój magnes jest znacznie potężniejszy. Ręcznie przeciągaj jaja do piwnicy.",
        playManual: "GRAJ W WYZWANIE",
        adamGameOver: "KONIEC GRY! Kura umarła z głodu. Restart Adama i Ewy...",
        locked: "ZABLOKOWANE",
    },
    sv: {
        loading: "LADDAR...",
        startingFarm: "Startar gård",
        money: "PENGAR:",
        ranking: "RANKNING",
        wipeSave: "RADERA SPARA",
        shopTitle: "Butik",
        buyChicken: "Köp kyckling",
        buyChickenDesc: "En ny värpande vän. (+1 Kyckling)",
        happyPetting: "Glatt Klappande",
        happyPettingDesc: "Klappa dina kycklingar för att göra dem glada. (-1.0s Lägghastighet)",
        eggValue: "Äggvärde",
        eggValueDesc: "Förbättrar grundläggande äggkvalitet. (x1.5 Värde)",
        eggRamp: "Äggramp",
        eggRampDesc: "Lägger till en trädkloss. (Mest värdelösa uppgraderingen)",
        maxFood: "Max Mat",
        maxFoodDesc: "Utökar matskålens kapacitet.",
        maxWater: "Max Vatten",
        maxWaterDesc: "Utökar vattenskålens kapacitet.",
        eggWasher: "Äggtvätt",
        eggWasherDesc: "Rengör ägg för att dramatiskt öka värdet. (x2 Värde)",
        autoFood: "Auto-Mat",
        autoFoodDesc: "Automatiserar matpåfyllning.",
        autoWater: "Auto-Vatten",
        autoWaterDesc: "Automatiserar vattenpåfyllning.",
        farmBelt: "Farmbälte",
        farmBeltDesc: "Transporterar automatiskt ängsägg rullande.",
        storageBelt: "Lagerbälte",
        storageBeltDesc: "Transporterar automatiskt lagrade ägg till marknaden.",
        refill: "Påfyllning",
        refillDesc: "Ökar kraften i manuell interaktion.",
        premiumFeed: "Premiumfoder (+5%)",
        premiumFeedDesc: "Chans att lägga premiuminägg. (+5% Chans / x2 Värde)",
        goldenEgg: "Guldägg (+1%)",
        goldenEggDesc: "Sällsynt chans att lägga guldägg. (+1% Chans / x5 Värde)",
        qualityStamp: "Kvalitetsstämpel",
        qualityStampDesc: "Certifierar äggkvaliteten för högre pris. (x2 Värde)",
        eggPackager: "Förpackare",
        eggPackagerDesc: "Förpackar ägg i dussin för enorm vinst. (x2 Värde)",
        premiumBox: "Premiumlåda",
        premiumBoxDesc: "Förpackar dina ägg i lyxig guldfolie. (x2 Värde)",
        farmMusic: "Gårdsmusik",
        farmMusicDesc: "Upplyftande låtar får kycklingar att gå snabbare. (+15% Hastighet)",
        proDiet: "Pro-Diet",
        proDietDesc: "Specialnäring som påskyndar värpningen. (-1.0s Tid)",
        dessertStomach: "Efterrättsmage",
        dessertStomachDesc: "Äter dubbelt så mycket, lägger dubbelt så många ägg.",
        magnetForce: "Magnetkraft",
        magnetForceDesc: "Magnetiserar din muspekare för att greppa ägg på håll.",
        theRooster: "Tuppen",
        theRoosterDesc: "En ståtlig följeslagare. Genererar en kyckling periodvis.",
        growthFormula: "Växtformel",
        growthFormulaDesc: "Påskyndar tiden för kycklingar att mogna till hönor. (-10s Tid)",
        asSeenOnTV: "Sett på TV",
        asSeenOnTVDesc: "En reklamfilm blir viral. Dubblar äggvärdet permanent! (x2 Värde)",
        retire: "Pensionera dig",
        wishlistOnSteam: "ÖNSKELISTA",
        takeABreak: "Ta en paus...",
        warning: "VARNING!",
        warningDesc: "Är du säker på att du vill radera ALLA framsteg?<br><br>Detta kan inte ångras!",
        cancel: "AVBRYT",
        wipeIt: "RADERA ALLT",
        pause: "PAUS",
        resume: "ÅTERUPPTA",
        speedrunRanking: "SPEEDRUN-RANKNING",
        connecting: "Ansluter...",
        speedrunWarning: "Speedrun-läget dubblar (x2) alla äggvärden.",
        startSpeedrun: "STARTA SPEEDRUN",
        normalMode: "NORMALT LÄGE",
        close: "STÄNG",
        newRecord: "NYTT REKORD!",
        time: "TID:",
        chickensFreed: "Frigivna Kycklingar:",
        enterName: "Ange ditt namn för rankningen:",
        community: "Gemenskap:",
        submitScore: "SKICKA",
        yourNamePlaceholder: "DITT NAMN",
        toggleMusic: "Växla musik",
        toggleInfo: "Visa info",
        market: "MARKNAD",
        fill: "Fyll på",
        water: "VATTEN:",
        food: "MAT:",
        waterEmpty: "Inget vatten,",
        foodEmpty: "Ingen mat,",
        clickToRefill: "klicka för att fylla ",
        playtime: "Speltid:",
        eggsSold: "Sålda Ägg:",
        earnings: "Inkomster:",
        chickens: "Kycklingar:",
        selectCommunity: "-- VÄLJ --",
        challenges: "UTMANINGAR",
        chal1Title: "1. NORMAL (RELAX)",
        chal1Desc: "Ingen ranking, ingen brådska. Väx i din egen takt och nå pensionen säkert.",
        playMode: "SPELA NORMALT",
        chal2Title: "4. SPEEDRUN",
        chal2Desc: "Äggvärdena fördubblas (x2). Bli klar så snabbt som möjligt. Din tid hamnar på den globala rankingen!",
        viewGlobalRanking: "VISA GLOBAL RANKING",
        playSpeedrun: "SPELA SPEEDRUN",
        chal3Title: "2. ADAM & EVA",
        chal3Desc: "Du börjar med exakt 1 Tupp och 1 Höna. Återbefolka gården med massor av kärlek, Max 5 tuppar.",
        playAdam: "SPELA UTMANING",
        chal4Title: "3. ÄGGSTOCKNING",
        chal4Desc: "Gårdens rullband gick sönder! Men din magnet är mycket kraftfullare. Dra äggen manuellt till källaren.",
        playManual: "SPELA UTMANING",
        adamGameOver: "GAME OVER! En höna svalt ihjäl. Startar om Adam & Eva...",
        locked: "LÅST",
    },
    nl: {
        loading: "LADEN...",
        startingFarm: "Boerderij starten",
        money: "GELD:",
        ranking: "RANGLIJST",
        wipeSave: "VERWIJDER OPSLAG",
        shopTitle: "Winkel",
        buyChicken: "Koop Kip",
        buyChickenDesc: "Een nieuwe legvriend. (+1 Kip)",
        happyPetting: "Vrolijk Aaien",
        happyPettingDesc: "Aai je kippen om ze blij te maken. (-1.0s Legtijd)",
        eggValue: "Ei Waarde",
        eggValueDesc: "Verbetert de kwaliteit van eieren. (x1.5 Waarde)",
        eggRamp: "Eierhelling",
        eggRampDesc: "Voegt een houten blokje toe. (Meest nutteloze upgrade)",
        maxFood: "Max Voedsel",
        maxFoodDesc: "Vergroot de voerbakcapaciteit.",
        maxWater: "Max Water",
        maxWaterDesc: "Vergroot de waterbakcapaciteit.",
        eggWasher: "Eierwasser",
        eggWasherDesc: "Wast de eieren om hun marktwaarde te verhogen. (x2 Waarde)",
        autoFood: "Auto-Voedsel",
        autoFoodDesc: "Automatiseert het bijvullen van voedsel.",
        autoWater: "Auto-Water",
        autoWaterDesc: "Automatiseert het bijvullen van water.",
        farmBelt: "Boerderijriem",
        farmBeltDesc: "Vervoert weide-eieren automatisch naar beneden.",
        storageBelt: "Opslagriem",
        storageBeltDesc: "Vervoert opgeslagen eieren naar de markt.",
        refill: "Bijvullen",
        refillDesc: "Verhoogt de kracht van handmatig aanvullen.",
        premiumFeed: "Premium Voer (+5%)",
        premiumFeedDesc: "Kans op goud eieren. (+5% Kans / x2 Waarde)",
        goldenEgg: "Gouden Ei (+1%)",
        goldenEggDesc: "Kans op gouden eieren. (+1% Kans / x5 Waarde)",
        qualityStamp: "Kwaliteitszegel",
        qualityStampDesc: "Certificeert de eikwaliteit voor hogere prijs. (x2 Waarde)",
        eggPackager: "Verpakker",
        eggPackagerDesc: "Verpakt eieren per dozijn voor megawinst. (x2 Waarde)",
        premiumBox: "Premium Doos",
        premiumBoxDesc: "Wikkelt eieren in luxe goudfolie. (x2 Waarde)",
        farmMusic: "Boerderijmuziek",
        farmMusicDesc: "Vrolijke deuntjes maken kippen sneller. (+15% Snelheid)",
        proDiet: "Pro-Dieet",
        proDietDesc: "Speciale voeding die het leggen versnelt. (-1.0s Tijd)",
        dessertStomach: "Dessertmaag",
        dessertStomachDesc: "Eet 2x voedsel en legt 2x zoveel eieren.",
        magnetForce: "Magneetkracht",
        magnetForceDesc: "Magnetiseert de muis om eieren op afstand te pakken.",
        theRooster: "De Haan",
        theRoosterDesc: "Majestueuze metgezel. Genereert periodiek jongen.",
        growthFormula: "Groeiformule",
        growthFormulaDesc: "Versnelt rijpingstijd van kuikens. (-10s Tijd)",
        asSeenOnTV: "Net als tv",
        asSeenOnTVDesc: "Commercial gaat viraal. Verdubbelt alle eiwaarden! (x2 Waarde)",
        retire: "Met Pensioen",
        wishlistOnSteam: "VERLANGLIJST",
        takeABreak: "Neem even rust...",
        warning: "WAARSCHUWING!",
        warningDesc: "Weet je zeker dat je AL je voortgang wilt wissen?<br><br>Dit kan niet ongedaan worden gemaakt!",
        cancel: "ANNULEREN",
        wipeIt: "VERWIJDER ALLES",
        pause: "PAUZE",
        resume: "HERVATTEN",
        speedrunRanking: "SPEEDRUN RANGLIJST",
        connecting: "Verbinden...",
        speedrunWarning: "Speedrun Mode verdubbelt (x2) de eierwaarde.",
        startSpeedrun: "START SPEEDRUN",
        normalMode: "NORMAAL",
        close: "SLUITEN",
        newRecord: "NIEUW RECORD!",
        time: "TIJD:",
        chickensFreed: "Bevrijde Kippen:",
        enterName: "Voer je naam in voor de ranglijst:",
        community: "Community:",
        submitScore: "INDIENEN",
        yourNamePlaceholder: "JOUW NAAM",
        toggleMusic: "Muziek aan/uit",
        toggleInfo: "Info tonen",
        market: "MARKT",
        fill: "Vul",
        water: "WATER:",
        food: "VOEDSEL:",
        waterEmpty: "Geen water,",
        foodEmpty: "Geen voedsel,",
        clickToRefill: "klikken om vullen ",
        playtime: "Speeltijd:",
        eggsSold: "Eieren Verkocht:",
        earnings: "Inkomsten:",
        chickens: "Kippen:",
        selectCommunity: "-- KIEZEN --",
        challenges: "UITDAGINGEN",
        chal1Title: "1. NORMAAL (RELAX)",
        chal1Desc: "Geen ranglijst, geen haast. Groei op je eigen tempo en bereik veilig je pensioen.",
        playMode: "SPEEL NORMAAL",
        chal2Title: "4. SPEEDRUN",
        chal2Desc: "Eierwaarden zijn verdubbeld (x2). Voltooi het zo snel mogelijk. Je tijd komt op de wereldwijde ranglijst!",
        viewGlobalRanking: "BEKIJK WERELDWIJDE RANGLIJST",
        playSpeedrun: "SPEEL SPEEDRUN",
        chal3Title: "2. ADAM & EVA",
        chal3Desc: "Je begint met precies 1 Haan en 1 Kip. Herbevolk de boerderij met veel liefde, Max 5 hanen.",
        playAdam: "SPEEL UITDAGING",
        chal4Title: "3. EIERFILE",
        chal4Desc: "De lopende band is kapot! Maar je magneet is veel krachtiger. Sleep de eieren handmatig naar de kelder.",
        playManual: "SPEEL UITDAGING",
        adamGameOver: "GAME OVER! Een kip is verhongerd. Adam & Eva opnieuw starten...",
        locked: "VERGRENDELD",
    },
    vi: {
        loading: "ĐANG TẢI...",
        startingFarm: "Khởi động Trang trại",
        money: "TIỀN:",
        ranking: "XẾP HẠNG",
        wipeSave: "XÓA DỮ LIỆU",
        shopTitle: "Cửa hàng",
        buyChicken: "Mua Gà",
        buyChickenDesc: "Người bạn đẻ trứng mới. (+1 Gà)",
        happyPetting: "Vuốt ve Vui vẻ",
        happyPettingDesc: "Vuốt gà để làm chúng vui. (-1.0s Thời gian đẻ)",
        eggValue: "Giá trị Trứng",
        eggValueDesc: "Tăng chất lượng trứng cơ bản. (x1.5 Giá trị)",
        eggRamp: "Cầu trượt",
        eggRampDesc: "Thêm nêm gỗ. (Nâng cấp vô dụng nhất)",
        maxFood: "Tối đa Thức ăn",
        maxFoodDesc: "Mở rộng sức chứa máng thức ăn.",
        maxWater: "Tối đa Nước",
        maxWaterDesc: "Mở rộng sức chứa máng nước.",
        eggWasher: "Máy rửa trứng",
        eggWasherDesc: "Rửa trứng tăng mạnh giá thị trường. (x2 Giá trị)",
        autoFood: "Tự động Th.ăn",
        autoFoodDesc: "Tự động thêm thức ăn.",
        autoWater: "Tự động Nước",
        autoWaterDesc: "Tự động thêm nước.",
        farmBelt: "Băng chuyền",
        farmBeltDesc: "Tự động vận chuyển trứng.",
        storageBelt: "Băng chuyền Kho",
        storageBeltDesc: "Tự động vận chuyển trứng ra thị trường.",
        refill: "Lấp đầy",
        refillDesc: "Tăng sức mạnh của tương tác thủ công.",
        premiumFeed: "Cám Cao cấp (+5%)",
        premiumFeedDesc: "Cơ hội đẻ trứng cao cấp. (+5% Cơ hội / x2 Giá trị)",
        goldenEgg: "Trứng Vàng (+1%)",
        goldenEggDesc: "Cơ hội đẻ trứng vàng. (+1% Cơ hội / x5 Giá trị)",
        qualityStamp: "Tem Chất lượng",
        qualityStampDesc: "Chứng nhận chất lượng trứng. (x2 Giá trị)",
        eggPackager: "Máy Đóng gói",
        eggPackagerDesc: "Đóng gói trứng theo tá để thu lợi lớn. (x2 Giá trị)",
        premiumBox: "Hộp Cao cấp",
        premiumBoxDesc: "Bọc trứng bằng giấy nilon sang trọng. (x2 Giá trị)",
        farmMusic: "Nhạc Nông trại",
        farmMusicDesc: "Giai điệu vui vẻ giúp gà nhanh hơn. (+15% Tốc độ)",
        proDiet: "Ăn kiêng",
        proDietDesc: "Dinh dưỡng tăng tốc đẻ trứng. (-1.0s Thời gian)",
        dessertStomach: "Dạ dày Tráng miệng",
        dessertStomachDesc: "Ăn gấp 2 thức ăn, đẻ gấp 2 lần trứng.",
        magnetForce: "Lực Từ tính",
        magnetForceDesc: "Từ tính hóa con trỏ lấy trứng từ xa.",
        theRooster: "Gà Trống",
        theRoosterDesc: "Đồng hành oai vệ. Sản sinh 1 gà con định kỳ.",
        growthFormula: "Công thức Tăng trưởng",
        growthFormulaDesc: "Giảm thời gian trưởng thành. (-10s)",
        asSeenOnTV: "Lên TV",
        asSeenOnTVDesc: "Quảng cáo thịnh hành. X2 vĩnh viễn trứng! (x2)",
        retire: "Nghỉ hưu",
        wishlistOnSteam: "YÊU THÍCH",
        takeABreak: "Nghỉ tay nào...",
        warning: "CẢNH BÁO!",
        warningDesc: "Bạn có chắc muốn xóa TẤT CẢ tiến trình không?",
        cancel: "HỦY BỎ",
        wipeIt: "XÓA HẾT",
        pause: "TẠM DỪNG",
        resume: "TIẾP TỤC",
        speedrunRanking: "XẾP HẠNG TỐC ĐỘ",
        connecting: "Đang kết nối...",
        speedrunWarning: "Chế độ chạy tốc độ x2 giá trị trứng.",
        startSpeedrun: "BẮT ĐẦU CHẠY XẾP HẠNG",
        normalMode: "CHẾ ĐỘ THƯỜNG",
        close: "ĐÓNG",
        newRecord: "KỶ LỤC MỚI!",
        time: "T.GIAN:",
        chickensFreed: "Gà đã giải phóng:",
        enterName: "Nhập tên vào BXH:",
        community: "Cộng đồng:",
        submitScore: "GỬI ĐIỂM",
        yourNamePlaceholder: "TÊN CỦA BẠN",
        toggleMusic: "Bật/Tắt Nhạc",
        toggleInfo: "Hiện thông tin",
        market: "CHỢ",
        fill: "Đổ đầy",
        water: "NƯỚC:",
        food: "T.ĂN:",
        waterEmpty: "Hết nước,",
        foodEmpty: "Hết thức ăn,",
        clickToRefill: "nhấn đổ ",
        playtime: "Giờ chơi:",
        eggsSold: "Trứng bán:",
        earnings: "Thu nhập:",
        chickens: "Số gà:",
        selectCommunity: "-- CHỌN --",
        challenges: "THỬ THÁCH",
        chal1Title: "1. BÌNH THƯỜNG (RELAX)",
        chal1Desc: "Không có bảng xếp hạng, không vội vàng. Phát triển theo tốc độ của bạn và đạt được mục tiêu nghỉ hưu một cách an toàn.",
        playMode: "CHƠI BÌNH THƯỜNG",
        chal2Title: "4. SPEEDRUN",
        chal2Desc: "Giá trị trứng được nhân đôi (x2). Hoàn thành nhanh nhất có thể. Thời gian của bạn sẽ được ghi vào Bảng xếp hạng Toàn cầu!",
        viewGlobalRanking: "XEM BẢNG XẾP HẠNG",
        playSpeedrun: "CHƠI SPEEDRUN",
        chal3Title: "2. ADAM & EVA",
        chal3Desc: "Bạn bắt đầu chỉ với 1 Gà trống và 1 Gà mái. Hãy lấp đầy trang trại bằng tình yêu, Tối đa 5 gà trống.",
        playAdam: "CHƠI THỬ THÁCH",
        chal4Title: "3. KẸT TRỨNG",
        chal4Desc: "Băng chuyền trang trại bị hỏng! Nhưng nam châm của bạn mạnh mẽ hơn nhiều. Kéo trứng bằng tay xuống tầng hầm.",
        playManual: "CHƠI THỬ THÁCH",
        adamGameOver: "GAME OVER! Một con gà đã chết đói. Đang khởi động lại Adam & Eva...",
        locked: "ĐÃ KHÓA",
    },
    'zh-cn': {
        loading: "载入中...",
        startingFarm: "启动农场",
        money: "金钱:",
        ranking: "排行榜",
        wipeSave: "清除存档",
        shopTitle: "商店",
        buyChicken: "购买鸡",
        buyChickenDesc: "新的产蛋好伙伴。 (+1 鸡)",
        happyPetting: "快乐抚摸",
        happyPettingDesc: "抚摸你的鸡让它们开心。 (-1.0秒 产蛋时间)",
        eggValue: "鸡蛋价值",
        eggValueDesc: "提升所有鸡蛋的先天品质。 (x1.5 价值)",
        eggRamp: "鸡蛋坡道",
        eggRampDesc: "添加一个木楔。 (被评为最无用的升级)",
        maxFood: "食物上限",
        maxFoodDesc: "扩大食槽容量。",
        maxWater: "饮水上限",
        maxWaterDesc: "扩大水盆容量。",
        eggWasher: "洗蛋机",
        eggWasherDesc: "清洗鸡蛋以大幅提高其市场价值。 (x2 价值)",
        autoFood: "自动喂食",
        autoFoodDesc: "自动补充食物。",
        autoWater: "自动喂水",
        autoWaterDesc: "自动补充饮水。",
        farmBelt: "农场传送带",
        farmBeltDesc: "自动将草地上的鸡蛋运送下去。",
        storageBelt: "存货传送带",
        storageBeltDesc: "自动将储存的鸡蛋运送到市场。",
        refill: "补充",
        refillDesc: "提升手动互动的力量。",
        premiumFeed: "优质饲料 (+5%)",
        premiumFeedDesc: "有几率产下高品质的优质鸡蛋。 (+5% 几率 / x2 价值)",
        goldenEgg: "金蛋 (+1%)",
        goldenEggDesc: "有罕见几率产下传说的金蛋。 (+1% 几率 / x5 价值)",
        qualityStamp: "品质印章",
        qualityStampDesc: "向市场证明鸡蛋品质以获得更高价格。 (x2 价值)",
        eggPackager: "包装机",
        eggPackagerDesc: "将鸡蛋按打包装以获取巨额利润。 (x2 价值)",
        premiumBox: "高级包装盒",
        premiumBoxDesc: "用奢华的黑金工艺包装你的鸡蛋。 (x2 价值)",
        farmMusic: "农场音乐",
        farmMusicDesc: "播放欢快的曲调，让鸡移动得更快。 (+15% 速度)",
        proDiet: "专业饮食",
        proDietDesc: "加速产蛋的特殊营养。 (-1.0秒 时间)",
        dessertStomach: "甜点胃",
        dessertStomachDesc: "吃两倍的食物，产两倍的鸡蛋。",
        magnetForce: "磁力",
        magnetForceDesc: "让你的鼠标产生磁力，能远程吸取鸡蛋。",
        theRooster: "公鸡",
        theRoosterDesc: "威风凛凛的雄鸡。定期孵出1只小鸡。",
        growthFormula: "生长配方",
        growthFormulaDesc: "缩短小鸡长成母鸡的时间。 (-10秒 成熟时间)",
        asSeenOnTV: "电视明星",
        asSeenOnTVDesc: "一则广告让你的农场火了！所有鸡蛋价值永久翻倍！ (x2 价值)",
        retire: "退休",
        wishlistOnSteam: "愿望单",
        takeABreak: "休息一下吧...",
        warning: "警告！",
        warningDesc: "你确定要删除所有的进度吗？<br><br>此操作无法撤销！",
        cancel: "取消",
        wipeIt: "清除数据",
        pause: "暂停",
        resume: "继续",
        speedrunRanking: "速通排行榜",
        connecting: "连接服务器...",
        speedrunWarning: "速通模式下所有鸡蛋价值翻倍 (x2)。<br><br>只有在速通模式下游玩的记录会被上传到排行榜！",
        startSpeedrun: "开始速通",
        normalMode: "普通模式",
        close: "关闭",
        newRecord: "新记录！",
        time: "时间:",
        chickensFreed: "释放的鸡:",
        enterName: "输入你的名字以参与排行榜:",
        community: "社区:",
        submitScore: "提交分数",
        yourNamePlaceholder: "你的名字",
        toggleMusic: "切换音乐",
        toggleInfo: "显示信息",
        market: "市场",
        fill: "补充",
        water: "水:",
        food: "食物:",
        waterEmpty: "水箱空了,",
        foodEmpty: "食槽空了,",
        clickToRefill: "点击补充 ",
        playtime: "游戏时长:",
        eggsSold: "售出鸡蛋:",
        earnings: "收益:",
        chickens: "鸡群:",
        selectCommunity: "-- 选择 --"
    },
    ko: {
        loading: "로딩 중...",
        startingFarm: "농장 시작",
        money: "돈:",
        ranking: "랭킹",
        wipeSave: "세이브 삭제",
        shopTitle: "상점",
        buyChicken: "닭 구매",
        buyChickenDesc: "새로운 산란 친구. (+1 닭)",
        happyPetting: "쓰다듬기",
        happyPettingDesc: "닭을 쓰다듬어 행복하게 만드세요. (-1.0초 산란 시간)",
        eggValue: "달걀 가치",
        eggValueDesc: "모든 달걀의 기본 품질을 높입니다. (x1.5 가치)",
        eggRamp: "달걀 경사로",
        eggRampDesc: "나무 쐐기를 추가합니다. (가장 쓸데없는 업그레이드)",
        maxFood: "최대 먹이",
        maxFoodDesc: "먹이통의 용량을 늘립니다.",
        maxWater: "최대 물",
        maxWaterDesc: "물통의 용량을 늘립니다.",
        eggWasher: "달걀 세척기",
        eggWasherDesc: "달걀을 씻어 시장 가치를 크게 높입니다. (x2 가치)",
        autoFood: "자동 먹이",
        autoFoodDesc: "먹이를 자동으로 채웁니다.",
        autoWater: "자동 물",
        autoWaterDesc: "물을 자동으로 채웁니다.",
        farmBelt: "농장 컨베이어",
        farmBeltDesc: "농장의 달걀을 아래로 자동으로 운반합니다.",
        storageBelt: "창고 컨베이어",
        storageBeltDesc: "보관된 달걀을 시장으로 자동으로 운반합니다.",
        refill: "채우기",
        refillDesc: "달걀 수동 상호작용의 힘을 높입니다.",
        premiumFeed: "프리미엄 사료 (+5%)",
        premiumFeedDesc: "고급 달걀을 낳을 확률입니다. (+5% 확률 / x2 가치)",
        goldenEgg: "황금 달걀 (+1%)",
        goldenEggDesc: "전설의 황금 달걀을 낳을 희귀 확률. (+1% 확률 / x5 가치)",
        qualityStamp: "품질 도장",
        qualityStampDesc: "더 높은 가격을 위해 품질을 인증합니다. (x2 가치)",
        eggPackager: "달걀 포장기",
        eggPackagerDesc: "엄청난 이익을 위해 달걀을 단위로 포장합니다. (x2 가치)",
        premiumBox: "프리미엄 상자",
        premiumBoxDesc: "놀라운 무광 포장으로 포장합니다. (x2 가치)",
        farmMusic: "농장 음악",
        farmMusicDesc: "음악으로 닭들을 더 빨리 움직이게 합니다. (+15% 속도)",
        proDiet: "프로 식단",
        proDietDesc: "산란 속도를 높여주는 영양분입니다. (-1.0초 시간)",
        dessertStomach: "디저트 위장",
        dessertStomachDesc: "먹이를 두 배로 먹고 두 배의 달걀을 낳습니다.",
        magnetForce: "자석 힘",
        magnetForceDesc: "멀리 있는 달걀을 쉽게 잡도록 마우스를 자성화합니다.",
        theRooster: "수탉",
        theRoosterDesc: "주기적으로 1마리의 병아리를 부화시킵니다.",
        growthFormula: "성장 공식",
        growthFormulaDesc: "성장 시간을 줄여줍니다. (-10초 시간)",
        asSeenOnTV: "TV에 나온 농장",
        asSeenOnTVDesc: "모든 달걀 가치가 영원히 2배가 됩니다! (x2 가치)",
        retire: "은퇴하기",
        wishlistOnSteam: "찜하기",
        takeABreak: "잠시 휴식하세요...",
        warning: "경고!",
        warningDesc: "모든 진행 상황을 지우시겠습니까?<br><br>이 작업은 되돌릴 수 없습니다!",
        cancel: "취소",
        wipeIt: "전부 삭제",
        pause: "일시 정지",
        resume: "재개하기",
        speedrunRanking: "스피드런 랭킹",
        connecting: "서버 연결 중...",
        speedrunWarning: "스피드런 모드는 달걀 가치를 두 배(x2)로 만듭니다.",
        startSpeedrun: "스피드런 시작",
        normalMode: "일반 모드",
        close: "닫기",
        newRecord: "새로운 기록!",
        time: "시간:",
        chickensFreed: "해방된 닭:",
        enterName: "랭킹에 등록할 이름을 입력하세요:",
        community: "커뮤니티:",
        submitScore: "점수 제출",
        yourNamePlaceholder: "당신의 이름",
        toggleMusic: "음악 설정",
        toggleInfo: "정보 보기",
        market: "시장",
        fill: "채우기",
        water: "물:",
        food: "먹이:",
        waterEmpty: "물이 없습니다,",
        foodEmpty: "먹이가 없습니다,",
        clickToRefill: "클릭하여 채우기 ",
        playtime: "플레이 시간:",
        eggsSold: "판매된 달걀:",
        earnings: "수익:",
        chickens: "닭:",
        selectCommunity: "-- 선택하세요 --",
        challenges: "도전 과제",
        chal1Title: "1. 보통 (RELAX)",
        chal1Desc: "순위도, 서두를 필요도 없습니다. 자신의 페이스대로 성장하여 안전하게 은퇴 목표에 도달하세요.",
        playMode: "보통 플레이",
        chal2Title: "4. 스피드런",
        chal2Desc: "달걀 가치가 두 배(x2)가 됩니다. 가능한 한 빨리 완료하세요. 당신의 기록은 글로벌 랭킹에 올라갑니다!",
        viewGlobalRanking: "글로벌 랭킹 보기",
        playSpeedrun: "스피드런 플레이",
        chal3Title: "2. 아담과 이브",
        chal3Desc: "수탉 1마리와 암탉 1마리로 시작합니다. 사랑으로 농장을 다시 채우세요, 최대 수탉 5마리.",
        playAdam: "도전 과제 플레이",
        chal4Title: "3. 달걀 잼",
        chal4Desc: "농장 컨베이어 벨트가 끊어졌습니다! 하지만 자석은 훨씬 더 강력합니다. 달걀을 수동으로 지하실로 드래그하세요.",
        playManual: "도전 과제 플레이",
        adamGameOver: "게임 오버! 닭이 굶어 죽었습니다. 아담과 이브를 재시작합니다...",
        locked: "잠김",
    },
    ja: {
        loading: "ロード中...",
        startingFarm: "農場を開始",
        money: "お金:",
        ranking: "ランキング",
        wipeSave: "データー消去",
        shopTitle: "ショップ",
        buyChicken: "ニワトリを買う",
        buyChickenDesc: "新しい産卵仲間。 (+1 鶏)",
        happyPetting: "幸せのなでなで",
        happyPettingDesc: "鶏をなでて幸せにする。(-1.0秒 産卵時間)",
        eggValue: "卵の価値",
        eggValueDesc: "すべての卵の基本品質を向上させる。(x1.5 価値)",
        eggRamp: "卵のランプ",
        eggRampDesc: "木のくさびを追加。(最も無駄なアップグレード)",
        maxFood: "最大エサ",
        maxFoodDesc: "エサ箱の容量を拡大する。",
        maxWater: "最大水",
        maxWaterDesc: "水桶の容量を拡大する。",
        eggWasher: "卵洗浄機",
        eggWasherDesc: "卵を洗浄して市場価値を劇的に高める。(x2 価値)",
        autoFood: "自動エサ",
        autoFoodDesc: "エサを自動で補充する。",
        autoWater: "自動水",
        autoWaterDesc: "水を自動で補充する。",
        farmBelt: "農場ベルト",
        farmBeltDesc: "牧草地の卵を自動的に下へ運ぶ。",
        storageBelt: "保管ベルト",
        storageBeltDesc: "保管された卵を市場へ自動的に運ぶ。",
        refill: "補充",
        refillDesc: "手動操作のパワーを向上させる。",
        premiumFeed: "プレミアムエサ (+5%)",
        premiumFeedDesc: "高品質な卵を産む確率。(+5% 確率 / x2 価値)",
        goldenEgg: "金の卵 (+1%)",
        goldenEggDesc: "伝説の金の卵を産む確率。(+1% 確率 / x5 価値)",
        qualityStamp: "品質スタンプ",
        qualityStampDesc: "卵の品質を証明し価格を上げる。(x2 価値)",
        eggPackager: "卵パッカー",
        eggPackagerDesc: "莫大な利益のために卵をダースで箱詰めする。(x2 価値)",
        premiumBox: "プレミアムボックス",
        premiumBoxDesc: "豪華な黒と金の箔で卵を包む。(x2 価値)",
        farmMusic: "農場音楽",
        farmMusicDesc: "陽気な曲で鶏の動きが速くなる。(+15% 速度)",
        proDiet: "プロダイエット",
        proDietDesc: "産卵を早める特別な食事。(-1.0秒 時間)",
        dessertStomach: "デザートの胃袋",
        dessertStomachDesc: "エサを2倍食べ、2倍の卵を産む。",
        magnetForce: "磁力",
        magnetForceDesc: "離れた場所の卵を磁石のように引き寄せる。",
        theRooster: "雄鶏",
        theRoosterDesc: "威厳ある仲間。定期的にヒナを1羽生み出す。",
        growthFormula: "成長フォーミュラ",
        growthFormulaDesc: "ヒナが鶏に成長する時間を短縮する。(-10秒 時間)",
        asSeenOnTV: "テレビで話題",
        asSeenOnTVDesc: "あなたの農場のCMが話題に！卵の価値が永久に2倍。(x2 価値)",
        retire: "引退する",
        wishlistOnSteam: "ウィッシュリスト",
        takeABreak: "一休みして下さい...",
        warning: "警告!",
        warningDesc: "すべての進行状況を消去してもよろしいですか？<br><br>元に戻すことはできません！",
        cancel: "キャンセル",
        wipeIt: "消去する",
        pause: "一時停止",
        resume: "再開",
        speedrunRanking: "スピードラン ランキング",
        connecting: "サーバーに接続中...",
        speedrunWarning: "スピードランモードは卵の価値が2倍になります。<br><br>スピードランの記録のみがランキングに載ります！",
        startSpeedrun: "スピードラン開始",
        normalMode: "通常モード",
        close: "閉じる",
        newRecord: "新記録!",
        time: "時間:",
        chickensFreed: "解放された鶏:",
        enterName: "ランキングの名前を入力してください:",
        community: "コミュニティ:",
        submitScore: "スコアを送信",
        yourNamePlaceholder: "あなたの名前",
        toggleMusic: "音楽切替",
        toggleInfo: "情報表示",
        market: "市場",
        fill: "補充",
        water: "水:",
        food: "エサ:",
        waterEmpty: "水が空,",
        foodEmpty: "エサが空,",
        clickToRefill: "クリックで補充する ",
        playtime: "プレイ時間:",
        eggsSold: "売れた卵:",
        earnings: "収益:",
        chickens: "鶏:",
        selectCommunity: "-- 選択 --",
        challenges: "チャレンジ",
        chal1Title: "1. ノーマル (RELAX)",
        chal1Desc: "ランキングなし、焦る必要なし。自分のペースで成長し、無事に引退の目標に到達しましょう。",
        playMode: "ノーマルをプレイ",
        chal2Title: "4. スピードラン",
        chal2Desc: "卵の価値が2倍(x2)になります。できるだけ早くクリアしてください。あなたのタイムはグローバルランキングに登録されます！",
        viewGlobalRanking: "グローバルランキングを見る",
        playSpeedrun: "スピードランをプレイ",
        chal3Title: "2. アダムとイヴ",
        chal3Desc: "雄鶏1羽と雌鶏1羽から始めます。愛で農場を再びいっぱいにしましょう。雄鶏は最大5羽まで。",
        playAdam: "チャレンジをプレイ",
        chal4Title: "3. エッグジャム",
        chal4Desc: "農場のベルトコンベアが壊れました！しかし、あなたの磁石ははるかに強力です。卵を手動で地下室にドラッグしてください。",
        playManual: "チャレンジをプレイ",
        adamGameOver: "ゲームオーバー！鶏が餓死しました。アダムとイヴを再起動しています...",
        locked: "ロック済み",
    },
    es: {
        loading: "CARGANDO...",
        startingFarm: "Iniciando Granja",
        money: "Dinero:",
        ranking: "CLASIFICACION",
        wipeSave: "BORRAR PARTIDA",
        shopTitle: "Tienda",
        buyChicken: "Comprar Gallina",
        buyChickenDesc: "Una nueva amiga ponedora. (+1 Gallina)",
        happyPetting: "Mimos Felices",
        happyPettingDesc: "Acaricia a tus gallinas para hacerlas felices. Cada caricia reduce el tiempo de puesta. (-1.0s Tiempo de puesta por caricia)",
        eggValue: "Valor de Huevo",
        eggValueDesc: "Mejora la calidad innata de todos los huevos. (x1.5 Valor Base)",
        eggRamp: "Rampa de Huevos",
        eggRampDesc: "Evita que los huevos se atasquen. (Votado como la mejora más inútil)",
        maxFood: "Comida Max",
        maxFoodDesc: "Expande la capacidad del comedero.",
        maxWater: "Agua Max",
        maxWaterDesc: "Expande la capacidad del cuenco de agua.",
        eggWasher: "Lavadora de Huevos",
        eggWasherDesc: "Limpia los huevos para aumentar drásticamente su valor en el mercado. (x2 Multiplicador de Valor)",
        autoFood: "Auto-Comida",
        autoFoodDesc: "Automatiza el rellenado de comida.",
        autoWater: "Auto-Agua",
        autoWaterDesc: "Automatiza el rellenado de agua.",
        farmBelt: "Cinta de Granja",
        farmBeltDesc: "Transporta automáticamente los huevos de la pradera hacia abajo.",
        storageBelt: "Cinta de Almacen",
        storageBeltDesc: "Transporta automáticamente los huevos almacenados al mercado.",
        refill: "Rellenar",
        refillDesc: "Aumenta el poder de interacción manual.",
        premiumFeed: "Pienso Premium (+5%)",
        premiumFeedDesc: "Una oportunidad de poner huevos premium de alta calidad. (+5% Probabilidad / x2 Valor)",
        goldenEgg: "Huevo Dorado (+1%)",
        goldenEggDesc: "Una oportunidad rara de poner huevos dorados legendarios. (+1% Probabilidad / x5 Valor)",
        qualityStamp: "Sello de Calidad",
        qualityStampDesc: "Certifica la calidad del huevo para un mayor precio de mercado. (x2 Multiplicador de Valor)",
        eggPackager: "Empaquetador",
        eggPackagerDesc: "Empaqueta los huevos por docenas para beneficios masivos. (x2 Multiplicador de Valor)",
        premiumBox: "Caja Premium",
        premiumBoxDesc: "Envuelve tus huevos en un lujoso paquete negro mate y dorado. (x2 Multiplicador de Valor)",
        farmMusic: "Musica de Granja",
        farmMusicDesc: "Toca melodías animadas, haciendo que las gallinas se muevan más rápido. (+15% Velocidad)",
        proDiet: "Dieta Pro",
        proDietDesc: "Nutrición especializada que acelera la puesta de huevos. (-1.0s Tiempo de puesta)",
        dessertStomach: "Estomago de Postre",
        dessertStomachDesc: "Come el doble de comida y pone el doble de huevos entre comidas.",
        magnetForce: "Fuerza Magnetica",
        magnetForceDesc: "Magnetiza tu ratón para coger más huevos a distancia. (+5px Radio / +1 Capacidad)",
        theRooster: "El Gallo",
        theRoosterDesc: "Un compañero majestuoso. Ayuda a crecer tu rebaño con el tiempo. (Genera 1 pollito periódicamente)",
        growthFormula: "Formula de Crecimiento",
        growthFormulaDesc: "Acelera el tiempo que tarda un pollito en madurar y convertirse en gallina. (-10s Tiempo de Maduración)",
        asSeenOnTV: "Anunciado en TV",
        asSeenOnTVDesc: "Un anuncio sobre tu granja se vuelve viral. ¡Duplica permanentemente el valor de venta de todos los huevos! (x2 Multiplicador de Valor)",
        retire: "Retirarse",
        wishlistOnSteam: "¡AÑADIR A STEAM!",
        takeABreak: "Tomate un descanso...",
        warning: "¡ADVERTENCIA!",
        warningDesc: "¿Estás seguro de que quieres borrar TODO tu progreso?<br><br>¡Esto no se puede deshacer!",
        cancel: "CANCELAR",
        wipeIt: "BORRAR TODO",
        pause: "PAUSA",
        resume: "REANUDAR",
        speedrunRanking: "CLASIFICACION SPEEDRUN",
        connecting: "Conectando al servidor...",
        speedrunWarning: "El Modo Speedrun duplica (x2) todos los valores de los huevos.<br><br>¡Solo las partidas en Modo Speedrun se suben a la clasificación!",
        startSpeedrun: "COMENZAR SPEEDRUN",
        normalMode: "MODO NORMAL",
        close: "CERRAR",
        newRecord: "¡NUEVO RECORD!",
        time: "TIEMPO:",
        chickensFreed: "Gallinas Liberadas:",
        enterName: "Introduce tu nombre para la clasificación global:",
        community: "Comunidad:",
        submitScore: "ENVIAR PUNTUACION",
        yourNamePlaceholder: "TU NOMBRE",

        // JS Texts
        market: "MERCADO",
        fill: "Llenar",
        water: "AGUA:",
        food: "COMIDA:",
        waterEmpty: "Agua agotada,",
        foodEmpty: "Comida agotada,",
        clickToRefill: "clic para rellenar ",
        playtime: "Tiempo jugado:",
        eggsSold: "Huevos Vendidos:",
        earnings: "Ganancias:",
        chickens: "Gallinas:",
        selectCommunity: "-- SELECCIONA COMUNIDAD --",
        challenges: "RETOS",
        chal1Title: "1. NORMAL (RELAX)",
        chal1Desc: "Sin ranking, sin prisas. Crece a tu propio ritmo hasta llegar al Retiro final.",
        playMode: "JUGAR NORMAL",
        chal2Title: "4. SPEEDRUN",
        chal2Desc: "Los huevos valen x2. Completalo lo mas rapido posible. ¡Tu tiempo subirá al Ranking Global!",
        viewGlobalRanking: "VER RANKING GLOBAL",
        playSpeedrun: "JUGAR SPEEDRUN",
        chal3Title: "2. ADÁN Y EVA",
        chal3Desc: "Empiezas con 1 Gallo y 1 Gallina. Repuebla la granja con mucho amor, Max 5 gallos.",
        playAdam: "JUGAR RETO",
        chal4Title: "3. ATASCO DE HUEVOS",
        chal4Desc: "¡La cinta de la granja se rompió! Pero tu imán es mucho mas poderoso. Arrastra manualmente los huevos al sótano.",
        playManual: "JUGAR RETO",
        adamGameOver: "¡GAME OVER! Una gallina ha muerto de hambre. Reiniciando Adán y Eva...",
        locked: "BLOQUEADO",
    },
    en: {
        loading: "LOADING...",
        startingFarm: "Starting Farm",
        money: "Money:",
        ranking: "RANKING",
        wipeSave: "WIPE SAVE",
        shopTitle: "Shop",
        buyChicken: "Buy Chicken",
        buyChickenDesc: "A new laying friend. (+1 Chicken)",
        happyPetting: "Happy Petting",
        happyPettingDesc: "Pet your chickens to make them happy. Each pet reduces the time it takes to lay an egg. (-1.0s Lay Time per pet)",
        eggValue: "Egg Value",
        eggValueDesc: "Enhances the innate quality of all eggs. (x1.5 Base Value)",
        eggRamp: "Egg Ramp",
        eggRampDesc: "Adds a wooden wedge to bounce falling eggs cleanly onto the underground belt. (Voted the most useless upgrade)",
        maxFood: "Max Food",
        maxFoodDesc: "Expands trough capacity.",
        maxWater: "Max Water",
        maxWaterDesc: "Expands water basin capacity.",
        eggWasher: "Egg Washer",
        eggWasherDesc: "Cleans eggs to dramatically increase their market value. (x2 Value Multiplier)",
        autoFood: "Auto-Food",
        autoFoodDesc: "Automates food refilling.",
        autoWater: "Auto-Water",
        autoWaterDesc: "Automates water refilling.",
        farmBelt: "Farm Belt",
        farmBeltDesc: "Automatically transports meadow eggs below.",
        storageBelt: "Storage Belt",
        storageBeltDesc: "Automatically transports stored eggs to market.",
        refill: "Refill",
        refillDesc: "Boosts manual interaction power.",
        premiumFeed: "Premium Feed (+5%)",
        premiumFeedDesc: "A chance to lay high-quality premium eggs. (+5% Chance / x2 Value)",
        goldenEgg: "Golden Egg (+1%)",
        goldenEggDesc: "A rare chance to lay legendary golden eggs. (+1% Chance / x5 Value)",
        qualityStamp: "Quality Stamp",
        qualityStampDesc: "Certifies egg quality for a higher market price. (x2 Value Multiplier)",
        eggPackager: "Egg Packager",
        eggPackagerDesc: "Boxes eggs in dozens for massive profits. (x2 Value Multiplier)",
        premiumBox: "Premium Box",
        premiumBoxDesc: "Wraps your eggs in luxurious matte black and gold foil packaging. (x2 Value Multiplier)",
        farmMusic: "Farm Music",
        farmMusicDesc: "Plays upbeat tunes, making chickens move faster. (+15% Speed)",
        proDiet: "Pro Diet",
        proDietDesc: "Specialized nutrition that speeds up egg laying. (-1.0s Lay Time)",
        dessertStomach: "Dessert Stomach",
        dessertStomachDesc: "Eats x2 food and lays twice as many eggs between meals.",
        magnetForce: "Magnet Force",
        magnetForceDesc: "Magnetizes your cursor to grab more eggs at a distance. (+5px Radius / +1 Capacity)",
        theRooster: "The Rooster",
        theRoosterDesc: "A majestic companion. Helps grow your flock over time. (Spawns 1 chick periodically)",
        growthFormula: "Growth Formula",
        growthFormulaDesc: "Speeds up the time it takes a chick to mature into a laying hen. (-10s Maturation Time)",
        asSeenOnTV: "As Seen On TV",
        asSeenOnTVDesc: "A commercial about your farm goes viral. Permanently doubles the sale value of all eggs! (x2 Value Multiplier)",
        retire: "Retire",
        wishlistOnSteam: "WISHLIST ON STEAM!",
        takeABreak: "Take a break...",
        warning: "WARNING!",
        warningDesc: "Are you sure you want to delete ALL progress?<br><br>This cannot be undone!",
        cancel: "CANCEL",
        wipeIt: "WIPE IT",
        pause: "PAUSE",
        resume: "RESUME",
        speedrunRanking: "SPEEDRUN RANKING",
        connecting: "Connecting to server...",
        speedrunWarning: "Speedrun Mode doubles (x2) all egg values.<br><br>Only Speedrun runs are uploaded to the Ranking!",
        startSpeedrun: "START SPEEDRUN",
        normalMode: "NORMAL MODE",
        close: "CLOSE",
        newRecord: "NEW RECORD!",
        time: "TIME:",
        chickensFreed: "Chickens Freed:",
        enterName: "Enter your name for the global ranking:",
        community: "Community:",
        submitScore: "SUBMIT SCORE",
        yourNamePlaceholder: "YOUR NAME",

        // JS Texts
        market: "MARKET",
        fill: "Fill",
        water: "WATER:",
        food: "FOOD:",
        waterEmpty: "Water empty,",
        foodEmpty: "Food empty,",
        clickToRefill: "click to refill ",
        playtime: "Playtime:",
        eggsSold: "Eggs Sold:",
        earnings: "Earnings:",
        chickens: "Chickens:",
        selectCommunity: "-- SELECT COMMUNITY --",
        challenges: "CHALLENGES",
        chal1Title: "1. NORMAL (RELAX)",
        chal1Desc: "No ranking, no penalties. Grow at your own pace and reach the retirement destination safely.",
        playMode: "PLAY NORMAL",
        chal2Title: "4. SPEEDRUN",
        chal2Desc: "Egg values are doubled (x2). Reach the end as fast as you can. Your final time goes to the Global Ranking!",
        viewGlobalRanking: "VIEW GLOBAL RANKING",
        playSpeedrun: "PLAY SPEEDRUN",
        chal3Title: "2. ADAM & EVE",
        chal3Desc: "Start with strictly 1 Rooster and 1 Hen. Repopulate the farm with love, Max 5 roosters.",
        playAdam: "PLAY CHALLENGE",
        chal4Title: "3. EGG JAM",
        chal4Desc: "The Farm belt broke! But your magnet is much more powerful. Drag eggs manually to the basement.",
        playManual: "PLAY CHALLENGE",
        adamGameOver: "GAME OVER! A chicken starved. Restarting Adam & Eve...",
        locked: "LOCKED",
    }
};

let savedLang = localStorage.getItem('chickenIdleLang');
let currentLang = savedLang ? savedLang : (navigator.language.startsWith('es') ? 'es' : (navigator.language.startsWith('ru') ? 'ru' : (navigator.language.startsWith('tr') ? 'tr' : (navigator.language.startsWith('de') ? 'de' : (navigator.language.startsWith('fr') ? 'fr' : (navigator.language.startsWith('it') ? 'it' : (navigator.language.startsWith('pt') ? 'pt-br' : (navigator.language.startsWith('pl') ? 'pl' : (navigator.language.startsWith('sv') ? 'sv' : (navigator.language.startsWith('nl') ? 'nl' : (navigator.language.startsWith('vi') ? 'vi' : (navigator.language.startsWith('zh') ? 'zh-cn' : (navigator.language.startsWith('ko') ? 'ko' : (navigator.language.startsWith('ja') ? 'ja' : 'en'))))))))))))));

window.changeLanguage = function (langStr, playSnd = false) {
    if (playSnd && !window.isMusicMuted) {
        let snd = new Audio('audio/pop-buy.wav');
        snd.volume = 0.8;
        snd.play().catch(e => { });
    }

    if (I18N[langStr]) {
        currentLang = langStr;
        localStorage.setItem('chickenIdleLang', currentLang);
        window.P2P_FONT = ['ja', 'zh-cn'].includes(currentLang) ? 'DotGothic16' : (['ko', 'vi'].includes(currentLang) ? 'sans-serif' : 'Press Start 2P');
        window.P2P_SCALE = (window.P2P_FONT === 'Press Start 2P') ? 1.0 : 1.35;

        let targetFont = `"${window.P2P_FONT}", monospace, sans-serif`;
        document.body.style.fontFamily = targetFont;

        // Multiplicador visual: Press Start 2P es muy voluminosa.
        let scaleFactor = window.P2P_SCALE;

        // Aplicar a todos los elementos excepto a las zonas restringidas y cuadrícula de idiomas
        let elems = document.querySelectorAll('button:not(.lang-btn), h1, h2, h3, p, span, input, select, div, a');
        elems.forEach(e => {
            // Ignoramos todo lo que pertenezca a cajas que nunca deben ser traducidas o escaladas
            if (e.closest('#ranking-list') || e.closest('#ranking-status') || e.closest('#topbar')) return;

            if (e.style) {
                e.style.fontFamily = targetFont;

                // Leer el CSS real aplicado por style.css o inline
                if (!e.dataset.origFontSize) {
                    let comp = window.getComputedStyle(e).fontSize;
                    if (comp && comp.includes('px')) {
                        e.dataset.origFontSize = parseFloat(comp);
                    }
                }

                // Aplicamos el factor
                if (e.dataset.origFontSize) {
                    e.style.fontSize = (parseFloat(e.dataset.origFontSize) * scaleFactor) + 'px';
                }
            }
        });

        // Proteger el branding forzándolo inline preventivamente contra el body proxy
        let topBarH1 = document.querySelector('#topbar h1');
        if (topBarH1) topBarH1.style.fontFamily = `\'Press Start 2P\', monospace`;

        let speedTimer = document.querySelector('#speedrun-timer');
        if (speedTimer) speedTimer.style.fontFamily = `\'Press Start 2P\', monospace`;

        let rankStatus = document.querySelector('#ranking-status');
        if (rankStatus) rankStatus.style.fontFamily = `\'Press Start 2P\', monospace`;

        let rankList = document.querySelector('#ranking-list');
        if (rankList) rankList.style.fontFamily = `\'Press Start 2P\', monospace`;

        document.querySelectorAll('.lang-btn').forEach(b => b.style.fontFamily = `\'Press Start 2P\', monospace`);

        let transAuthor = document.getElementById('trans-author');
        if (transAuthor) {
            if (currentLang === 'tr') {
                transAuthor.setAttribute('data-i18n', 'transByEge');
            } else {
                transAuthor.setAttribute('data-i18n', (currentLang === 'en' || currentLang === 'es') ? 'transByJc' : 'transByAI');
            }
        }

        // Resaltar visualmente el botón del idioma activo
        document.querySelectorAll('.lang-btn').forEach(btn => {
            if (btn.id === 'lang-' + currentLang) {
                btn.style.transform = 'scale(1.15)';
                btn.style.border = '2px solid white';
                btn.style.zIndex = '10';
                btn.style.boxShadow = '0px 0px 10px rgba(255,255,255,0.5)';
            } else {
                btn.style.transform = 'scale(1)';
                btn.style.border = 'none';
                btn.style.zIndex = '1';
                btn.style.boxShadow = 'none';
            }
        });

        if (window.applyTranslations) window.applyTranslations();
    }
}

// Inyectar cadenas base
I18N['en'].transByJc = 'Translated by <a href="https://www.reddit.com/user/WranglerIntrepid3817/" target="_blank" style="color:#e056fd; text-decoration: none;">Jc</a>';
I18N['es'].transByJc = 'Traducido por <a href="https://www.reddit.com/user/WranglerIntrepid3817/" target="_blank" style="color:#e056fd; text-decoration: none;">Jc</a>';
I18N['en'].transByAI = 'Translation generated by AI';
I18N['es'].transByAI = 'Traducción generada por IA';
I18N['tr'].transByEge = 'Translated by <a href="https://x.com/egyldz" target="_blank" style="color:#e056fd; text-decoration: none;">Ege Yıldız</a>';
I18N['en'].badTrans = 'Bad translation? Help us!';
I18N['es'].badTrans = '¿Mala traducción? ¡Ayúdanos en Reddit!';

Object.keys(I18N).forEach(k => {
    if (!I18N[k].transByAI) I18N[k].transByAI = 'Translation generated by AI';
    if (!I18N[k].badTrans) I18N[k].badTrans = 'Bad translation? Help us!';
    if (!I18N[k].transByJc) I18N[k].transByJc = I18N['en'].transByJc;
});

window.P2P_FONT = ['ja', 'zh-cn'].includes(currentLang) ? 'DotGothic16' : (['ko', 'vi'].includes(currentLang) ? 'sans-serif' : 'Press Start 2P');
window.P2P_SCALE = (window.P2P_FONT === 'Press Start 2P') ? 1.0 : 1.35;
let targetFontInit = `"${window.P2P_FONT}", monospace, sans-serif`;
document.body.style.fontFamily = targetFontInit;
document.addEventListener('DOMContentLoaded', () => { window.changeLanguage(currentLang); });

window.t = function (key) {
    if (I18N[currentLang] && I18N[currentLang][key]) return I18N[currentLang][key];
    if (I18N['en'][key]) return I18N['en'][key];
    return key;
}

window.applyTranslations = function () {
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        el.innerHTML = window.t(key);
    });
    document.querySelectorAll('[data-i18n-title]').forEach(el => {
        const key = el.getAttribute('data-i18n-title');
        const translated = window.t(key);
        el.setAttribute('data-title', translated);
        const descDiv = el.querySelector('.shop-desc-text');
        if (descDiv) descDiv.innerHTML = translated;
    });
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
        const key = el.getAttribute('data-i18n-placeholder');
        el.setAttribute('placeholder', window.t(key));
    });
}

window.addEventListener('DOMContentLoaded', window.applyTranslations);
